// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cocwfqqzeoumlyxbrlkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNvY3dmcXF6ZW91bWx5eGJybGtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MjIzNjIsImV4cCI6MjA1OTQ5ODM2Mn0.O6ciSjq2hjOjkMSvJl4dMfVMLAXehwBqLVE4AaeP-hw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);